### ISSUE TITLE
[ Feature Request ] Remove products from DOM

### ISSUE THREAD

**Issue by herrlegno** [sdelquin/sendhereplz#37]
Maybe a good feature is to be able to configure to delete the unshippable products.

Nice extension, I'm loving it!.

**Comment by scorpion421** [comment]
I know, kinda late to reply because I found this add-on just currently.

For uBlock Origin, add the following:
`amazon.de##div[class*="shp-not-deliverable-product"]`
Replace .de with the extension of Amazon you're using. Like .com.

For Stylish or Stylus, simply go to Amazon and add a new style:
`div[class*="shp-not-deliverable-product"] {display:none !important}`

**Comment by sdelquin** [comment]
@scorpion421 Thank you very much for your support. Quite interesting! 🚀

**Comment by sdelquin** [comment]
@scorpion421 We've added [your suggestion to the README](https://github.com/sdelquin/sendhereplz#hide-unshippable-items).

**Comment by herrlegno** [comment]
I'm closing this issue, as now Readme address this. Thank you!
